{
    'name': 'Product Attribute Manager',
    'version': '8.0.1.0',
    'category': 'Product',
    'summary': 'Add attributes to products',
    'author':
        'Wytze Jan Riedstra, NetAndCo, Akretion, Prisnet Telecommunications SA'
        ', MONK Software, Odoo Community Association (OCA)',
    'license': 'LGPL-3',
    'depends': [
        'product_brand',
        'mob_extra_images',
    ],
    'data': [
        'views/product_attributemanager.xml',
        'views/product.xml',
        'views/product_attributeset.xml',
        'views/product_color.xml',
        'views/product_options.xml',
        'views/product_buggies_agecategory.xml',
        'views/product_buggies_maxcarryweight.xml',
        'views/product_buggies_numberofwheels.xml',
        'views/product_carriers_directionofuse.xml',
        'views/product_carriers_maxcarryweight.xml',
        'views/product_carriers_type.xml',
        'views/product_carseats_agecategory.xml',
        'views/product_carseats_childlength.xml',
        'views/product_carseats_childweight.xml',
        'views/product_carseats_directionofuse.xml',
        'views/product_carseats_installmethod.xml',
        'views/product_clothes_season.xml',
        'views/product_clothes_size.xml',
        'views/product_highchairs_agecategory.xml',
        'views/product_highchairs_material.xml',
        'views/product_monitors_maxrange.xml',
        'views/product_rockers_maxcarryweight.xml',
        'views/product_strollers_numberofwheels.xml',
        'views/product_textiles_size.xml',
        'views/product_toys_agecategory.xml',
        'views/product_toys_type.xml',
        'security/ir.model.access.csv',
    ],
    'installable': True,
    'post_load': 'post_load',
}
